"""adds scanned table

Revision ID: 1772d4d8dcd6
Revises: f9e00729b8e3
Create Date: 2025-02-26 11:24:13.467746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1772d4d8dcd6'
down_revision = 'f9e00729b8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanned')
    # ### end Alembic commands ###
