"""changes asset_id to string

Revision ID: 676117c944c0
Revises: d99917ef2171
Create Date: 2025-02-28 09:50:58.140541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676117c944c0'
down_revision = 'd99917ef2171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanned', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanned', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
