"""updates scanned table

Revision ID: c4c0c741d378
Revises: f78b9e5e1304
Create Date: 2025-03-02 09:11:12.749740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c0c741d378'
down_revision = 'f78b9e5e1304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('scanned_asset_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('scanned_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('asset_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('scanned_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('scanned_asset_id_fkey', 'assets', ['asset_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
