"""changes unuque

Revision ID: cac271c9c001
Revises: a6762f8a75a4
Create Date: 2025-02-23 22:40:29.692360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac271c9c001'
down_revision = 'a6762f8a75a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=225),
               existing_nullable=False)
        batch_op.drop_constraint('assets_category_key', type_='unique')
        batch_op.drop_constraint('assets_condition_key', type_='unique')
        batch_op.drop_constraint('assets_description_key', type_='unique')
        batch_op.drop_constraint('assets_name_key', type_='unique')
        batch_op.drop_constraint('assets_space_key', type_='unique')
        batch_op.drop_constraint('assets_status_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_unique_constraint('assets_status_key', ['status'])
        batch_op.create_unique_constraint('assets_space_key', ['space'])
        batch_op.create_unique_constraint('assets_name_key', ['name'])
        batch_op.create_unique_constraint('assets_description_key', ['description'])
        batch_op.create_unique_constraint('assets_condition_key', ['condition'])
        batch_op.create_unique_constraint('assets_category_key', ['category'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
