"""minor fix

Revision ID: f78b9e5e1304
Revises: 676117c944c0
Create Date: 2025-02-28 10:31:09.001550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78b9e5e1304'
down_revision = '676117c944c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
                       existing_type=sa.String(length=80),
                       type_=sa.BigInteger(),
                       existing_nullable=False,
                       postgresql_using='asset_id::bigint')
        
    with op.batch_alter_table('scanned', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.Integer(),
               existing_nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanned', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
